### ISSUE TITLE
Don't show welcome screen after the first time

### ISSUE THREAD

**Issue by keith-kurak** [infinitered/cr-2024-intermediate-workshop-template#10]
It shows on every refresh. I thought this wasn't the case in standard Ignite. I don't see a variable to suppress it after the first view, and it's the index route inside the `(app)` group, so it makes sense that it's showing.

It'd be good to not see that every time during the workshop. I guess the easiest thing would be to just delete the index route :-).

**Comment by frankcalise** [comment]
done!
